# Generated by Django 5.0.3 on 2024-03-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_column='category', db_comment='Название категории. Ограничение на 255 символов', help_text='Название категории', max_length=255, unique=True, verbose_name='Категория')),
                ('description', models.CharField(db_column='description', db_comment='Описание категории. Ограничение на 255 символов', help_text='Описание категории', max_length=255, verbose_name='Описание')),
                ('slug', models.SlugField(db_column='slug', db_comment='Слаг, помогающий сформировать url адрес для конкретной категории. Ограничение на 255 символов', help_text='Слаг для категорий', max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'db_table': 'category',
                'db_table_comment': 'Категории для постов',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
